import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Export report data as an Excel-compatible CSV (UTF-8 BOM for correct ₹/unicode rendering).
 */
export function exportToCSV({ columns, rows, filename = 'parkmaster-report' }) {
  const BOM = '\uFEFF';
  const escape = (cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`;
  const csv = [
    columns.map(escape).join(','),
    ...rows.map(row => row.map(escape).join(','))
  ].join('\r\n');

  const blob = new Blob([BOM + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}-${Date.now()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export report data as a professionally formatted PDF using jsPDF + AutoTable.
 */
export function exportToPDF({ title, subtitle, columns, rows, summary = [], businessName = 'ParkMaster Parking' }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Letterhead
  doc.setFillColor(20, 22, 27);
  doc.rect(0, 0, pageWidth, 26, 'F');
  doc.setFillColor(250, 204, 21);
  doc.rect(0, 26, pageWidth, 1.5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(businessName.toUpperCase(), 14, 12);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 200, 200);
  doc.text(title, 14, 19);

  doc.setTextColor(120, 120, 120);
  doc.text(subtitle, pageWidth - 14, 19, { align: 'right' });

  // Summary block
  let startY = 36;
  if (summary.length > 0) {
    doc.setTextColor(30, 30, 30);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    summary.forEach((s, i) => {
      const x = 14 + i * 60;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(130, 130, 130);
      doc.text(s.label.toUpperCase(), x, startY);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(20, 22, 27);
      doc.text(String(s.value), x, startY + 7);
    });
    startY += 16;
  }

  // Data table
  autoTable(doc, {
    startY,
    head: [columns],
    body: rows,
    theme: 'striped',
    headStyles: {
      fillColor: [20, 22, 27],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'left'
    },
    bodyStyles: { fontSize: 8.5, textColor: [50, 50, 50] },
    alternateRowStyles: { fillColor: [246, 247, 249] },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      // Footer
      doc.setFontSize(7.5);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by ParkMaster · ${new Date().toLocaleString('en-IN')}`,
        14,
        doc.internal.pageSize.getHeight() - 8
      );
      doc.text(`Page ${data.pageNumber}`, pageWidth - 14, doc.internal.pageSize.getHeight() - 8, { align: 'right' });
    }
  });

  doc.save(`${title.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.pdf`);
}

/**
 * Trigger the browser print dialog for the visible .print-area element.
 */
export function printReport() {
  window.print();
}